  CREATE TABLE MYSTUDY.STUDENT 
   (	ID VARCHAR2(20 BYTE), 
	NAME VARCHAR2(30 BYTE), 
	KOR NUMBER(3,0), 
	ENG NUMBER(3,0), 
	MATH NUMBER(3,0), 
	TOT NUMBER(3,0), 
	AVG NUMBER(5,2)
   );
   
   